// Assignment_4/react/src/components/Login.js
import React, { useState } from 'react';
import { Link, useNavigate } from 'react-router-dom';
import axios from 'axios';
import { useAuth } from '../context/AuthContext';

function Login() {
  const [username, setUsername] = useState('');
  const [password, setPassword] = useState('');
  const [loginMessage, setLoginMessage] = useState('');
  const navigate = useNavigate();
  const { login } = useAuth();

  const handleSubmit = async (e) => {
    e.preventDefault();
    try {
      const response = await axios.post('http://localhost:3000/auth/login', { username, password });
      const { token, user } = response.data;
      if (token) {
        localStorage.setItem('token', token);
        login(user);  // Assuming `login` sets the user state in your AuthContext
        navigate('/');  // Navigate to the home page after successful login
      }
    } catch (error) {
      setLoginMessage(error.response?.data?.message || 'Login failed');
    }
  };

  return (
    <section className="login_section">
      <div className="section_container">
        <h2 className="section_title">Login to Your Account</h2>
        <form onSubmit={handleSubmit}>
          <div className="field">
            <label htmlFor="username">Username</label>
            <input 
              type="text" 
              id="username" 
              placeholder="Enter your username" 
              required 
              value={username}
              onChange={(e) => setUsername(e.target.value)}
            />
          </div>
          <div className="field">
            <label htmlFor="password">Password</label>
            <input 
              type="password" 
              id="password" 
              placeholder="Enter your password" 
              required 
              value={password}
              onChange={(e) => setPassword(e.target.value)}
            />
          </div>
          <button className="button" type="submit">Login</button>
          {loginMessage && <p className="error_message">{loginMessage}</p>}
        </form>
        <p>Don't have an account? <Link to="/signup">Sign up here</Link></p>
      </div>
    </section>
  );
}

export default Login;

// Assignment_4/Project-root/CofeeCornerApp/src/app/login/login.component.ts
import { Component } from '@angular/core';
import { IonicModule } from '@ionic/angular';
import { FormsModule } from '@angular/forms';
import { Router } from '@angular/router';
import axios from 'axios';

@Component({
  selector: 'app-login',
  standalone: true,
  imports: [IonicModule, FormsModule],
  templateUrl: './login.component.html',
  styleUrls: ['./login.component.scss'],
})
export class LoginComponent {
  username = '';
  password = '';
  loginMessage = '';

  
  constructor(private router: Router) {}

  async login() {
      // Retrieve users from local storage
      const users = JSON.parse(localStorage.getItem('users') || '[]');
      const user = users.find((user: any) => user.username.trim() === this.username.trim() && user.password === this.password);

      if (user) {
        alert(`Login successful! Welcome, ${user.username}.`);
        // Navigate to a specific page (e.g., home or dashboard)
        localStorage.setItem('accountType', 'storeManager');
        this.router.navigate(['/home']);
      } else {
        alert('Invalid username or password.');
      }
    }
}

<ion-header>
  <ion-toolbar>
    <ion-title>Login</ion-title>
  </ion-toolbar>
</ion-header>

<ion-content>
  <section class="login_section">
    <div class="section_container">
      <h2 class="section_title">Login to Your Account</h2>
      <form (submit)="$event.preventDefault(); login()">
        <ion-item>
          <ion-label position="floating">Username</ion-label>
          <ion-input [(ngModel)]="username" type="text" placeholder="Enter your username" required></ion-input>
        </ion-item>
        <ion-item>
          <ion-label position="floating">Password</ion-label>
          <ion-input [(ngModel)]="password" type="password" placeholder="Enter your password" required></ion-input>
        </ion-item>
        <ion-button type="submit" expand="block">Login</ion-button>
      </form>
      <p class="error_message">{{ loginMessage }}</p>
      <p>Don&apos;t have an account? <ion-router-link routerLink="/signup">Sign up here</ion-router-link></p>
    </div>
  </section>
</ion-content>
