// Assignment_4/Project-root/CofeeCornerApp/src/app/home/home.component.ts
import { Component, OnInit } from '@angular/core';
import { Router, RouterModule } from '@angular/router';
import { IonicModule } from '@ionic/angular';

@Component({
  selector: 'app-home',
  imports: [IonicModule, RouterModule],
  templateUrl: './home.component.html',
  styleUrls: ['./home.component.scss'],
  standalone: true,
})
export class HomeComponent  implements OnInit {
  accountType = '';

  constructor(private router: Router) { 
    this.updateAccountType();
    window.addEventListener('storage', this.updateAccountType.bind(this));
  }

  updateAccountType() {
    this.accountType = localStorage.getItem('accountType') || '';
  }

  ngOnInit() {}

  navigateToCafes() {
    this.router.navigate(['/cafes']);
  }

  navigateToCafeManager() {
    this.updateAccountType();
    if (this.accountType === 'storeManager') {
      this.router.navigate(['/cafes']);
    } else {
      alert('You must be logged in as a store manager to add cafes.');
    }
  }

  ngOnDestroy() {
    window.removeEventListener('storage', this.updateAccountType.bind(this)); // Cleanup event listener
  }

}

<ion-header>
  <ion-toolbar>
    <ion-buttons slot="start">
      <ion-button routerLink="/login">Login</ion-button>
      <ion-button routerLink="/signup">Sign Up</ion-button>
    </ion-buttons>
    <ion-title>Home</ion-title>
  </ion-toolbar>
</ion-header>

<ion-content>
  <section class="hero_section">
    <div class="hero_container">
      <div class="text_section">
        <h2>Find your perfect Coffee</h2>
        <h3>Discover the Magic of the perfect cup</h3>
        <p>
          Welcome to our coffee paradise, where every bean tells a story and
          every cup sparks joy. Help us reach everyone.
        </p>
        <div class="hero_section_button">
          <ion-button (click)="navigateToCafes()" expand="block">Find your perfect Cafe</ion-button>
          <ion-button (click)="navigateToCafeManager()" expand="block">Got your own cafe?</ion-button>
        </div>
      </div>
      <div class="image_section">
        <img src="assets/images/cofffee_image.png" alt="Coffee" />
      </div>
    </div>
  </section>
</ion-content>

// Assignment_4/react/src/components/Home.js
import React from 'react';
import { Link } from 'react-router-dom';
import About from './About';
import Contact from './Contact';

function Home() {
  return (
    <>
      <section className="hero_section">
        <div className="section_container">
          <div className="hero_container">
            <div className="text_section">
              <h2>Find your perfect Coffee</h2>
              <h3>Discover the Magic of the perfect cup</h3>
              <p>
                Welcome to our coffee paradise, where every bean tells a story and
                every cup sparks, And you can help it reach everyone.
              </p>

              <div className="hero_section_button">
                <Link to="/cafes" className="button">Find your perfect Cafe</Link>
                <Link to="/login" className="button">Got your own cafe?</Link>
              </div>
            </div>

            <div className="image_section">
              <img src="/cofffee_image.png" alt="Coffee" />
            </div>
          </div>
        </div>
      </section>

      <About />
      <Contact />
    </>
  );
}

export default Home;
