// Assignment_4/Project-root/CofeeCornerApp/src/app/signup/signup.component.ts
import { Component } from '@angular/core';
import axios from 'axios';
import { IonicModule } from '@ionic/angular';
import { FormsModule } from '@angular/forms';
import { Router } from '@angular/router';

@Component({
  selector: 'app-signup',
  standalone: true,
  imports: [IonicModule, FormsModule],
  templateUrl: './signup.component.html',
  styleUrls: ['./signup.component.scss'],
})
export class SignupComponent {
  username = '';
  password = '';
  confirmPassword = '';
  accountType = '';
  signupMessage = '';

  constructor (private router: Router) {}

  signup() {
    if (this.password !== this.confirmPassword) {
      this.signupMessage = 'Passwords do not match.';
      return;
    }

    const users = JSON.parse(localStorage.getItem('users') || '[]');

      users.push({ username: this.username, password: this.password, accountType: this.accountType });
      localStorage.setItem('users', JSON.stringify(users));
      alert('Account created successfully!');
      setTimeout(() => {
        this.router.navigate(['/login']); // Navigate to login page
      }, 500);
    }
}


<ion-header>
  <ion-toolbar>
    <ion-title>Sign Up</ion-title>
  </ion-toolbar>
</ion-header>

<ion-content>
  <section class="signup_section">
    <form (submit)="$event.preventDefault(); signup()">
      <h2>Create Your Account</h2>
      <ion-item>
        <ion-label position="floating">Username</ion-label>
        <ion-input [(ngModel)]="username" type="text" required></ion-input>
      </ion-item>
      <ion-item>
        <ion-label position="floating">Password</ion-label>
        <ion-input [(ngModel)]="password" type="password" required></ion-input>
      </ion-item>
      <ion-item>
        <ion-label position="floating">Confirm Password</ion-label>
        <ion-input [(ngModel)]="confirmPassword" type="password" required></ion-input>
      </ion-item>
      <ion-item>
        <ion-label position="floating">Account Type</ion-label>
        <ion-select [(ngModel)]="accountType" placeholder="Select Account Type" required>
          <ion-select-option value="customer">Customer</ion-select-option>
          <ion-select-option value="storeManager">Store Manager</ion-select-option>
        </ion-select>
      </ion-item>
      <ion-button type="submit" expand="block">Sign Up</ion-button>
    </form>
    <p class="error_message">{{ signupMessage }}</p>
  </section>
</ion-content>

// Assignment_4/react/src/components/Signup.js
import React, { useState } from 'react';
import { useNavigate } from 'react-router-dom';
import axios from 'axios';

function Signup() {
  const [username, setUsername] = useState('');
  const [password, setPassword] = useState('');
  const [confirmPassword, setConfirmPassword] = useState('');
  const [accountType, setAccountType] = useState('');
  const [signupMessage, setSignupMessage] = useState('');
  const navigate = useNavigate();

  const handleSubmit = async (e) => {
    e.preventDefault();

    if (password !== confirmPassword) {
      setSignupMessage("Passwords do not match");
      return;
    }

    try {
      const response = await axios.post("http://localhost:3000/auth/signup", {
        username,
        password,
        accountType
      });

      if (response.status === 201) {
        setSignupMessage("Signup successful!");
        setUsername('');
        setPassword('');
        setConfirmPassword('');
        setAccountType('');
        setTimeout(() => navigate('/login'), 2000);
      }
    } catch (error) {
      setSignupMessage(error.response?.data?.message || "Signup failed");
    }
  };

  return (
    <div className="signup_section">
      <form onSubmit={handleSubmit}>
        <h2>Create Your Account</h2>
        
        <div className="field">
          <label htmlFor="userid">Username</label>
          <input 
            type="text" 
            id="userid" 
            required 
            value={username}
            onChange={(e) => setUsername(e.target.value)}
          />
        </div>

        <div className="field">
          <label htmlFor="password">Password</label>
          <input 
            type="password" 
            id="password" 
            required 
            value={password}
            onChange={(e) => setPassword(e.target.value)}
          />
        </div>

        <div className="field">
          <label htmlFor="confirmPassword">Confirm Password</label>
          <input 
            type="password" 
            id="confirmPassword" 
            required 
            value={confirmPassword}
            onChange={(e) => setConfirmPassword(e.target.value)}
          />
        </div>

        <div className="field">
          <label htmlFor="accountType">Account Type</label>
          <select 
            id="accountType" 
            required 
            value={accountType}
            onChange={(e) => setAccountType(e.target.value)}
          >
            <option value="">Select Account Type</option>
            <option value="customer">Customer</option>
            <option value="storeManager">Store Manager</option>
          </select>
        </div>

        <button type="submit" className="button">Sign Up</button>
      </form>
      {signupMessage && <p>{signupMessage}</p>}
    </div>
  );
}

export default Signup;
